[package]
name = "glow-protocol"
version = "1.0.0"
authors = ["Glow Protocol"]
edition = "2018"
description = "Common helpers for Glow protocol"
license = "Apache-2.0"
repository = ""
homepage = "https://glowyield.com"
documentation = "https://docs.glowyield.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw0 = "0.8.0"
cw20 = "0.8.0"
cosmwasm-bignumber = "2.2.0"
cosmwasm-std = "0.16.0"
cosmwasm-storage = "0.16.0"
terra-cosmwasm = "2.2.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }


[profile.dev]
overflow-checks = true

[profile.release]
overflow-checks = true
